[package]
name = "trex"
version = "0.1.5"
authors = ["Colin Ray <r.colinray@gmail.com>"]

[dependencies]
vec_map = "0.6.0"
bit-set = "0.4.0"
lazy_static = "0.1.15"

[dev-dependencies]
ansi_term = "0.7.2"
